import enum
from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, String, Text, Date, DateTime,
    Boolean, ForeignKey, Enum, Numeric, JSON, UniqueConstraint,
)
from sqlalchemy.orm import relationship
from .database import Base


class Priority(str, enum.Enum):
    low = "low"
    medium = "medium"
    high = "high"


class OccurrenceStatus(str, enum.Enum):
    upcoming = "upcoming"
    completed = "completed"
    skipped = "skipped"
    overdue = "overdue"


class TaskStatus(str, enum.Enum):
    todo = "todo"
    in_progress = "in_progress"
    done = "done"
    cancelled = "cancelled"


class TaskRecurrence(str, enum.Enum):
    none = "none"
    daily = "daily"
    weekly = "weekly"
    biweekly = "biweekly"
    monthly = "monthly"
    quarterly = "quarterly"
    semiannual = "semiannual"
    yearly = "yearly"


class WeekendShift(str, enum.Enum):
    back = "back"                   # Sat/Sun → preceding Friday
    forward = "forward"             # Sat/Sun → following Monday
    back_sat_only = "back_sat_only" # Saturday → Friday, Sunday unchanged
    nearest = "nearest"             # Saturday → Friday, Sunday → Monday


class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), unique=True, nullable=False)
    color = Column(String(7), default="#3b82f6")
    icon = Column(String(10), default="📅")
    description = Column(Text)

    events = relationship("Event", back_populates="category")


class CreditCard(Base):
    __tablename__ = "credit_cards"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    issuer = Column(String(100))
    last_four = Column(String(4))

    # Statement close date — fixed day of month
    statement_close_day = Column(Integer)       # None if cycle-based
    grace_period_days = Column(Integer)         # days close→due; None if fixed due day
    weekend_shift = Column(Enum(WeekendShift))  # how to shift weekend dates

    # Rolling cycle (e.g. U.S. Bank Altitude Go 29-day cycle)
    cycle_days = Column(Integer)
    cycle_reference_date = Column(Date)

    # Fixed due day overrides (mutually exclusive with grace_period_days)
    due_day_same_month = Column(Integer)   # due = this day of close month
    due_day_next_month = Column(Integer)   # due = this day of month after close

    # Annual fee
    annual_fee_month = Column(Integer)     # month the fee posts; None = no annual fee

    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    events = relationship(
        "Event",
        back_populates="credit_card",
        cascade="all, delete-orphan",
    )


class Event(Base):
    """
    A recurring (or one-time) event template.

    rrule stores an RFC 5545 RRULE string, e.g.:
        FREQ=YEARLY;BYMONTH=6;BYMONTHDAY=15
        FREQ=MONTHLY;BYMONTHDAY=25
        FREQ=MONTHLY;INTERVAL=6
    Special sentinels handled by the recurrence service:
        EASTER          → Easter Sunday
        EASTER-N/+N     → N days before/after Easter
    Leave rrule NULL for a one-time event (uses dtstart only).
    Credit-card events are generated by the credit card service and have
    rrule=NULL and a non-null credit_card_id.
    """
    __tablename__ = "events"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(200), nullable=False)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=False)
    credit_card_id = Column(Integer, ForeignKey("credit_cards.id", ondelete="CASCADE"), nullable=True)

    rrule = Column(Text)
    dtstart = Column(Date, nullable=False)
    dtend_rule = Column(Date)
    duration_days = Column(Integer, default=1)

    description = Column(Text)
    location = Column(String(300))
    reminder_days = Column(JSON, default=[7, 1])
    priority = Column(Enum(Priority), default=Priority.medium)
    amount = Column(Numeric(10, 2))

    is_active = Column(Boolean, default=True)
    generates_tasks = Column(Boolean, default=False)
    gcal_calendar_id = Column(String(200))

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    category = relationship("Category", back_populates="events")
    credit_card = relationship("CreditCard", back_populates="events")
    occurrences = relationship(
        "Occurrence", back_populates="event", cascade="all, delete-orphan"
    )


class Occurrence(Base):
    """A single generated instance of a recurring event."""
    __tablename__ = "occurrences"
    __table_args__ = (
        UniqueConstraint("event_id", "occurrence_date", name="uq_event_occurrence_date"),
    )

    id = Column(Integer, primary_key=True, index=True)
    event_id = Column(Integer, ForeignKey("events.id", ondelete="CASCADE"), nullable=False)
    occurrence_date = Column(Date, nullable=False, index=True)
    status = Column(Enum(OccurrenceStatus), default=OccurrenceStatus.upcoming)
    notes = Column(Text)

    gcal_event_id = Column(String(200))
    synced_at = Column(DateTime)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    event = relationship("Event", back_populates="occurrences")
    tasks = relationship("Task", back_populates="occurrence")


class Person(Base):
    __tablename__ = "persons"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    email = Column(String(200))

    tasks = relationship("Task", back_populates="assignee")


class Task(Base):
    __tablename__ = "tasks"

    id = Column(Integer, primary_key=True, index=True)
    occurrence_id = Column(Integer, ForeignKey("occurrences.id", ondelete="SET NULL"), nullable=True)
    category_id = Column(Integer, ForeignKey("categories.id", ondelete="SET NULL"), nullable=True)
    title = Column(String(200), nullable=False)
    description = Column(Text)
    status = Column(Enum(TaskStatus), default=TaskStatus.todo)
    priority = Column(Enum(Priority), default=Priority.medium)
    assignee_id = Column(Integer, ForeignKey("persons.id", ondelete="SET NULL"), nullable=True)
    due_date = Column(Date)
    estimated_minutes = Column(Integer)
    recurrence = Column(Enum(TaskRecurrence), default=TaskRecurrence.none)

    gtask_id = Column(String(200))
    synced_at = Column(DateTime)

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    occurrence = relationship("Occurrence", back_populates="tasks")
    category = relationship("Category")
    assignee = relationship("Person", back_populates="tasks")
    subtasks = relationship("Subtask", back_populates="task", cascade="all, delete-orphan")


class Subtask(Base):
    __tablename__ = "subtasks"

    id = Column(Integer, primary_key=True, index=True)
    task_id = Column(Integer, ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False)
    title = Column(String(200), nullable=False)
    status = Column(Enum(TaskStatus), default=TaskStatus.todo)
    due_date = Column(Date)
    order = Column(Integer, default=0)

    gtask_id = Column(String(200))

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    task = relationship("Task", back_populates="subtasks")
